### ISSUE TITLE
bash scripts/install_ext.sh in Windows

### ISSUE THREAD

**Issue by pegahsalehi** [ashawkey/RAD-NeRF#13]
Hi @ashawkey 
Is it possible to install these libraries on Windows?

```
pip install ./freqencoder
pip install ./shencoder
pip install ./gridencoder
pip install ./raymarching
```

Thanks in advance for your help!

**Comment by tylersky1993** [comment]
The problem has been solved!

[https://github.com/NVlabs/nvdiffrec/issues/35#issuecomment-1147749506](url)

**Comment by williamgladeye** [comment]
> The problem has been solved!
> 
> [https://github.com/NVlabs/nvdiffrec/issues/35#issuecomment-1147749506](url)

sorry how was this resolved? link seems dead

**Comment by tylersky1993** [comment]
https://github.com/NVlabs/nvdiffrec/issues/35#issuecomment-1147749506
I think this link works!

**Comment by tylersky1993** [comment]
> > The problem has been solved!
> > [https://github.com/NVlabs/nvdiffrec/issues/35#issuecomment-1147749506](url)
> 
> sorry how was this resolved? link seems dead

https://github.com/NVlabs/nvdiffrec/issues/35#issuecomment-1147749506
I think this link works!

**Comment by ataraxyz** [comment]
Does anyone have this repo running on Windows? I am running all sorts of issues with requirements etc. The link above helped install NVLabs but not this repo entirely. 

Would love to get it going, anyone had success?

**Comment by waityousea** [comment]
bash scripts/install_ext.sh在unbuntu中执行这个命令，所有安装都失败了，请问怎么解决？

**Comment by pegahsalehi** [comment]
According to the link, I was able to install them. Adding the path `C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\Hostx64\x64` to the environment is all that is needed

**Comment by huangxin168** [comment]
> bash scripts/install_ext.sh在unbuntu中执行这个命令，所有安装都失败了，请问怎么解决？

same

**Comment by waityousea** [comment]
问题：/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
      530 |         operator=(_Functor&& __f)
          |                                                                                                                                                  ^ 
    /usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
    
答案：解决问题的网址 https://github.com/NVIDIA/nccl/issues/650
这无济于事，至少在 Debian 中没有。
但是，有帮助的是 /usr/include/c++/*/bits/std_function.h 中进行以下两个更改：

433+行（近似值）：

  template<typename _Functor,
           typename _Constraints = _Requires<_Callable<_Functor>>>
    function(_Functor&& __f)
    //noexcept(_Handler<_Functor>::template _S_nothrow_init<_Functor>()) // CUDA BOTCHES THIS
    : _Function_base()
529+行（近似值）：

  template<typename _Functor>
    _Requires<_Callable<_Functor>, function&>
    operator=(_Functor&& __f)
    //noexcept(_Handler<_Functor>::template _S_nothrow_init<_Functor>()) // CUDA BOTCHES THIS
    {
      function(std::forward<_Functor>(__f)).swap(*this);
      return *this;
    }
注释掉指示的部分可以解决编译问题。出于某种原因，当该部分存在时，NVCC会搞砸编译。它预处理C++代码，并以无法编译的方式错误地更改模板签名。
    
So How to Define THRUST_IGNORE_CUB_VERSION_CHECK? or how to resolve the issue?
I tried change setup.py
define_macros += [("THRUST_IGNORE_CUB_VERSION_CHECK", True)]
or
define_macros += [("THRUST_IGNORE_CUB_VERSION_CHECK", 1)]

**Comment by Muhammad0073121** [comment]
I'm facing the same issue while running the .sh script
Can someone help me : 


Subzero@MSI MINGW64 /c/Audio2face/RAD-NeRF (main)
$ bash scripts/install_ext.sh
Processing c:\audio2face\rad-nerf\freqencoder
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  [17 lines of output]
  Traceback (most recent call last):
    File "c:\users\subzero\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "c:\users\subzero\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\users\subzero\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\Subzero\AppData\Local\Temp\pip-build-env-mj2uo_qf\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "C:\Users\Subzero\AppData\Local\Temp\pip-build-env-mj2uo_qf\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
      self.run_setup()
    File "C:\Users\Subzero\AppData\Local\Temp\pip-build-env-mj2uo_qf\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\Subzero\AppData\Local\Temp\pip-build-env-mj2uo_qf\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 3, in <module>
  ModuleNotFoundError: No module named 'torch'
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Processing c:\audio2face\rad-nerf\shencoder
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  [17 lines of output]
  Traceback (most recent call last):
    File "c:\users\subzero\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "c:\users\subzero\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\users\subzero\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\Subzero\AppData\Local\Temp\pip-build-env-nsbti2pu\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "C:\Users\Subzero\AppData\Local\Temp\pip-build-env-nsbti2pu\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
      self.run_setup()
    File "C:\Users\Subzero\AppData\Local\Temp\pip-build-env-nsbti2pu\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\Subzero\AppData\Local\Temp\pip-build-env-nsbti2pu\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 3, in <module>
  ModuleNotFoundError: No module named 'torch'
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Processing c:\audio2face\rad-nerf\gridencoder
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  [17 lines of output]
  Traceback (most recent call last):
    File "c:\users\subzero\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "c:\users\subzero\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\users\subzero\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\Subzero\AppData\Local\Temp\pip-build-env-8o8e1ia3\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "C:\Users\Subzero\AppData\Local\Temp\pip-build-env-8o8e1ia3\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
      self.run_setup()
    File "C:\Users\Subzero\AppData\Local\Temp\pip-build-env-8o8e1ia3\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\Subzero\AppData\Local\Temp\pip-build-env-8o8e1ia3\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 3, in <module>
  ModuleNotFoundError: No module named 'torch'
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Processing c:\audio2face\rad-nerf\raymarching
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  [17 lines of output]
  Traceback (most recent call last):
    File "c:\users\subzero\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "c:\users\subzero\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\users\subzero\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\Subzero\AppData\Local\Temp\pip-build-env-rxj6rvm2\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "C:\Users\Subzero\AppData\Local\Temp\pip-build-env-rxj6rvm2\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
      self.run_setup()
    File "C:\Users\Subzero\AppData\Local\Temp\pip-build-env-rxj6rvm2\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\Subzero\AppData\Local\Temp\pip-build-env-rxj6rvm2\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 3, in <module>
  ModuleNotFoundError: No module named 'torch'
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by troyhuqihang** [comment]
@Muhammad0073121 I got the same problem. How do you solve this issue? Thank you.

**Comment by pegahsalehi** [comment]
@troyhuqihang, You should be aware that the Visual Studio version with CUDA installed on your PC is compatible. For me, `14.34.31933` with `CUDA 11.8` worked well.

Then you must add this path in env.
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\ `14.34.31933`\bin\Hostx64\x64

### Other steps are step-by-step like this:

1. conda create -n rad-nerf python=3.10
2. conda activate rad-nerf
3. pip install tensorflow
4. pip install torch -f https://download.pytorch.org/whl/torch_stable.html
5. pip install -r requirements.txt (delete torch in this file  )
6. pip install chardet
7. pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu116
8. pip install ./freqencoder
9. pip install ./shencoder
10. pip install ./gridencoder
11. pip install ./raymarching

Thant's it! Enjoy :)
