### ISSUE TITLE
RuntimeError: Given input size: (192x2x2). Calculated output size: (192x0x0). Output size is too small

### ISSUE THREAD

**Issue by shiyueGG** [ashawkey/RAD-NeRF#57]
==> Start Training Epoch 123, lr=0.000049 ...
loss=0.0002 (0.0011), lr=0.000045: :   4% 59/1647 [00:02<00:33, 47.29it/s]Traceback (most recent call last):
  File "main.py", line 235, in <module>
    trainer.train(train_loader, valid_loader, max_epoch)
  File "/root/RAD-NeRF/nerf/utils.py", line 906, in train
    self.train_one_epoch(train_loader)
  File "/root/RAD-NeRF/nerf/utils.py", line 1169, in train_one_epoch
    preds, truths, loss = self.train_step(data)
  File "/root/RAD-NeRF/nerf/utils.py", line 766, in train_step
    loss = loss + 0.01 * self.criterion_lpips(pred_rgb, rgb)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/lpips/lpips.py", line 119, in forward
    outs0, outs1 = self.net.forward(in0_input), self.net.forward(in1_input)
  File "/root/miniconda3/lib/python3.8/site-packages/lpips/pretrained_networks.py", line 85, in forward
    h = self.slice3(h)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/pooling.py", line 162, in forward
    return F.max_pool2d(input, self.kernel_size, self.stride,
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_jit_internal.py", line 422, in fn
    return if_false(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/functional.py", line 797, in _max_pool2d
    return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: Given input size: (192x2x2). Calculated output size: (192x0x0). Output size is too small
loss=0.0002 (0.0011), lr=0.000045: :   4% 60/1647 [00:02<01:05, 24.31it/s]

**Comment by chanchanalina** [comment]
Hi, I have the same problem，Have you found the solution yet？

**Comment by seanko** [comment]
可能是中间处理出来的数据有问题，我也是这这种情况，我看了一下中间数据处理都是马赛克

**Comment by muximuxi** [comment]
> 可能是中间处理出来的数据有问题，我也是这这种情况，我看了一下中间数据处理都是马赛克

请问侧脸数据可以处理吗？我现在有侧脸的，估计是嘴巴区域小了就运算不了，请问怎么解决？

**Comment by mannanoyed** [comment]
Hey did you find any solutions for the same
