### ISSUE TITLE
Installation Error for Encoder Extensions

### ISSUE THREAD

**Issue by AvirupJU** [ashawkey/RAD-NeRF#94]
Hi I am not able to install shencoder, freqencoder and gridencoder with pip. 
I am using ```python3.10 + torch1.13.1 + CUDA11.6```. I have gcc 7.5.0 and ninja 1.8.2 installed on my system.
Here is the full stack trace of the error:

```
  Building wheel for freqencoder (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [90 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building '_freqencoder' extension
      creating /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build
      creating /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310
      creating /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/home
      creating /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/home/ubuntu
      creating /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/home/ubuntu/shared_nfs
      creating /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/home/ubuntu/shared_nfs/efs
      creating /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/home/ubuntu/shared_nfs/efs/RADNeRF
      creating /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/home/ubuntu/shared_nfs/efs/RADNeRF
      creating /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder
      creating /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/src
      Emitting ninja build file /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/2] /opt/conda/bin/nvcc  -I/opt/conda/lib/python3.10/site-packages/torch/include -I/opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.10/site-packages/torch/include/TH -I/opt/conda/lib/python3.10/site-packages/torch/include/THC -I/opt/conda/include -I/opt/conda/include/python3.10 -c -c /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/src/freqencoder.cu -o /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/src/freqencoder.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_freqencoder -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75
      FAILED: /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/src/freqencoder.o
      /opt/conda/bin/nvcc  -I/opt/conda/lib/python3.10/site-packages/torch/include -I/opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.10/site-packages/torch/include/TH -I/opt/conda/lib/python3.10/site-packages/torch/include/THC -I/opt/conda/include -I/opt/conda/include/python3.10 -c -c /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/src/freqencoder.cu -o /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/src/freqencoder.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_freqencoder -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75
      In file included from /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/src/freqencoder.cu:7:0:
      /opt/conda/lib/python3.10/site-packages/torch/include/ATen/cuda/CUDAContext.h:10:10: fatal error: cusolverDn.h: No such file or directory
       #include <cusolverDn.h>
                ^~~~~~~~~~~~~~
      compilation terminated.
      [2/2] c++ -MMD -MF /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/src/bindings.o.d -pthread -B /opt/conda/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/conda/include -fPIC -O2 -isystem /opt/conda/include -fPIC -I/opt/conda/lib/python3.10/site-packages/torch/include -I/opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.10/site-packages/torch/include/TH -I/opt/conda/lib/python3.10/site-packages/torch/include/THC -I/opt/conda/include -I/opt/conda/include/python3.10 -c -c /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/src/bindings.cpp -o /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/src/bindings.o -O3 -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_freqencoder -D_GLIBCXX_USE_CXX11_ABI=0
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1900, in _run_ninja_build
          subprocess.run(
        File "/opt/conda/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/setup.py", line 33, in <module>
          setup(
        File "/opt/conda/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/opt/conda/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/opt/conda/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
          build_ext.build_extensions(self)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
          self._build_extensions_serial()
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
          self.build_extension(ext)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 547, in build_extension
          objects = self.compiler.compile(
        File "/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1573, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for freqencoder
  Running setup.py clean for freqencoder
Failed to build freqencoder
Installing collected packages: freqencoder
  Running setup.py install for freqencoder ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for freqencoder did not run successfully.
  │ exit code: 1
  ╰─> [94 lines of output]
      running install
      /opt/conda/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      building '_freqencoder' extension
      creating /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build
      creating /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310
      creating /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/home
      creating /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/home/ubuntu
      creating /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/home/ubuntu/shared_nfs
      creating /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/home/ubuntu/shared_nfs/efs
      creating /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/home/ubuntu/shared_nfs/efs/RADNeRF
      creating /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/home/ubuntu/shared_nfs/efs/RADNeRF
      creating /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder
      creating /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/src
      Emitting ninja build file /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/2] /opt/conda/bin/nvcc  -I/opt/conda/lib/python3.10/site-packages/torch/include -I/opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.10/site-packages/torch/include/TH -I/opt/conda/lib/python3.10/site-packages/torch/include/THC -I/opt/conda/include -I/opt/conda/include/python3.10 -c -c /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/src/freqencoder.cu -o /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/src/freqencoder.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_freqencoder -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75
      FAILED: /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/src/freqencoder.o
      /opt/conda/bin/nvcc  -I/opt/conda/lib/python3.10/site-packages/torch/include -I/opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.10/site-packages/torch/include/TH -I/opt/conda/lib/python3.10/site-packages/torch/include/THC -I/opt/conda/include -I/opt/conda/include/python3.10 -c -c /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/src/freqencoder.cu -o /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/src/freqencoder.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_freqencoder -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75
      In file included from /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/src/freqencoder.cu:7:0:
      /opt/conda/lib/python3.10/site-packages/torch/include/ATen/cuda/CUDAContext.h:10:10: fatal error: cusolverDn.h: No such file or directory
       #include <cusolverDn.h>
                ^~~~~~~~~~~~~~
      compilation terminated.
      [2/2] c++ -MMD -MF /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/src/bindings.o.d -pthread -B /opt/conda/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/conda/include -fPIC -O2 -isystem /opt/conda/include -fPIC -I/opt/conda/lib/python3.10/site-packages/torch/include -I/opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.10/site-packages/torch/include/TH -I/opt/conda/lib/python3.10/site-packages/torch/include/THC -I/opt/conda/include -I/opt/conda/include/python3.10 -c -c /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/src/bindings.cpp -o /home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/build/temp.linux-x86_64-cpython-310/home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/src/bindings.o -O3 -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_freqencoder -D_GLIBCXX_USE_CXX11_ABI=0
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1900, in _run_ninja_build
          subprocess.run(
        File "/opt/conda/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/ubuntu/shared_nfs/efs/RADNeRF/freqencoder/setup.py", line 33, in <module>
          setup(
        File "/opt/conda/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/opt/conda/lib/python3.10/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/opt/conda/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
          build_ext.build_extensions(self)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
          self._build_extensions_serial()
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
          self.build_extension(ext)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 547, in build_extension
          objects = self.compiler.compile(
        File "/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1573, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> freqencoder
```

**Comment by AvirupJU** [comment]
Okay, this one is a bit nuanced. ```cusolverDn.h``` is called during the installation but it is not available in torch site packages so it throws an error. To solve this first you need to locate the file using ```find /usr/ -name cusolverDn.h``` and then manually add the path in the terminal like:
```
export CPLUS_INCLUDE_PATH=/usr/local/cuda-11.6/include:$CPLUS_INCLUDE_PATH
export C_INCLUDE_PATH=/usr/local/cuda-11.6/include:$C_INCLUDE_PATH
```
Then you can proceed with the installation without issues.
